name: project-name Docs

remote_theme: dbones-labs/jekyll-docs-theme@v1.0.0

project:
  version: 1.0.0
  download_url: https://github.com/organisation-name/project-name/releases
  download_text: Download

license:
  software: Apache 2.0 License
  software_url: https://opensource.org/licenses/Apache-2.0

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/organisation-name/project-name
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/organisation-name/project-name
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/organisation-name/project-name
    - title: Issues
      icon: bug
      url: https://github.com/organisation-name/project-name/issues?state=open

ui:
  mode: 'dark' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: organisation-name
    repo: project-name
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: 

# Build settings